version: '3'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOME: ${PWD}
        BUNDLE_JOBS: 4
        RUBY_VERSION: 3.1.3
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:${PWD}
