version: '2'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=${PWD}
        - BUNDLE_JOBS=4
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres
    volumes:
      - .:${PWD}
    environment:
      - DATABASE_URL=postgres://postgres:@postgres
  spring:
    <<: *app_base
    ports: []
    command: spring server
    stdin_open: true
    tty: true
    pid: host
    environment:
      DATABASE_URL: postgres://postgres:@postgres
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:${PWD}
      - spring_data:/tmp/spring
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  spring_data:
