version: 2
jobs:
  build:
    working_directory: /home/circleci/love_equation
    parallelism: 2
    docker:
      - image: ruby:2.6.5
        environment:
          DATABASE_URL: postgres://postgres:@localhost
      - image: postgres:9.6
    steps:
      - run:
          name: Install System Dependencies
          command: apt-get update && apt-get install -y --no-install-recommends postgresql-client
      - checkout
      - restore_cache:
          keys:
            - love_equation-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - love_equation-{{ checksum "Gemfile.lock" }}
            - love_equation-
      - run:
          name: Install Rails Dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean
      - save_cache:
          key: love_equation-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: love_equation-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Create DB
          command: |
            bundle exec rails db:create
      - run:
          name: RSpec
          command: |
            bundle exec rspec --profile 10 \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
